version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- ps: 'dotnet restore .\src\ChaosMonkey.Guards.NetStandard.sln'
build:
  verbosity: minimal